name: Deploy Frontend

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 62.109.22.131
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
          script_stop: true
          script: |
            cd /var/www/natalcharts/frontend
            git pull origin main
            npm install
            npm run build
            pm2 restart natalcharts-frontend
